jQuery(document).ready(function(){
    jQuery('.owl-carousel').owlCarousel({
      items:1,
      loop:true,
      margin:10,
      autoHeight:true,
      autoplay:true,
      autoplayTimeout:6000,
      autoplayHoverPause:true
  });
});
